spring:
  profiles:
    default: local
---
spring:
  config:
    activate:
      on-profile: local

kafka:
  servers: localhost:9092
  topic: topic
  group-id: groupId


---
spring:
  config:
    activate:
      on-profile: test

kafka:
  servers: localhost:9092
  topic: topic
  group-id: groupId